### PR TITLE
added crash prevention and moved converter to folder

### PR DESCRIPTION
**Pull request by FireCubeStudios**

### CODE REVIEW

**Review by MarcAnt01 — CHANGES_REQUESTED** [review]
Everything all right, but the target version should remain unchanged

**Comment by FireCubeStudios** [comment]
> Everything all right, but the target version should remain unchanged

ok done

**Review by MarcAnt01 — CHANGES_REQUESTED** [review]
The pr contains also the VideoPreviewPage. I think it's better to include it in the proper pr, rather than in this one that is just about crash prevention

**Review by MarcAnt01 — APPROVED** [review]

**Comment by MarcAnt01** [comment]
Thanks for your contribution

**Pull request merged**
