### PR TITLE
 Add feature to go back using ESC button

### PR DESCRIPTION
**Pull request by itsWindows11**

### CODE REVIEW

**Comment by MarcAnt01** [comment]
Lgtm, could you add the same feature for `PlayerPage`?

**Comment by itsWindows11** [comment]
Ah wait, wrong branch

**Comment by MarcAnt01** [comment]
Are you sure? It looks like you're targeting the right one (in case you're talking about the target branch)

**Comment by itsWindows11** [comment]
> Are you sure? It looks like you're targeting the right one (in case you're talking about the target branch)

This is an out of date branch basically.

**Pull request closed without merging**
