### PR TITLE
Hungarian translation

### PR DESCRIPTION
**Pull request by gidano**
Hungarian translation

Regards,
gidano

### CODE REVIEW

**Review by MarcAnt01 — APPROVED** [review]

**Comment by MarcAnt01** [comment]
Thanks for your contribution

**Comment by gidano** [comment]
May I ask when can I enjoy the app in my native language?

**Comment by MarcAnt01** [comment]
> May I ask when can I enjoy the app in my native language?

Currently a major update is slowly making progress, I don’t really plan to release other versions in the meanwhile, to focus on it 100%

**Comment by gidano** [comment]
Thanks! 🙂

Filippo Fedeli ***@***.***> ezt írta (időpont: 2022. jún.
13., Hét 17:11):

**Pull request merged**
