### PR TITLE
UI refresh

### PR DESCRIPTION
**Pull request by itsWindows11**
Video showing how the UI looks like, currently:

https://user-images.githubusercontent.com/81253203/138315961-c0593e89-afe3-41e9-ba84-4e328cc695da.mp4

### CODE REVIEW

**Comment by itsWindows11** [comment]
I think the UI refresh is done, so this PR is almost ready to be merged.

**Comment by binamracode** [comment]
I am also not able to think of a better design for Recording UI rn. I will try to create some designs and post them here.

**Comment by nahomebssa** [comment]
For reference, this is how the Windows Voice Recorder app looks while recording:

Screenshot 2021-11-12 160134

The app is not in its final Windows-11-style form, but it's a good start.

**Comment by MarcAnt01** [comment]
@nahomebssa that's how I was inspired to make it in the previous versions of Fluent Screen Recorder. Whatever, we've had a discussion about it on Discord and we've decided to make a tiny bar like Xbox game bar from recording and expanding it afterwards

**Comment by onein528** [comment]
You should specify padding in ScrollViewer

Windows Apps:
image
Your changed app:
image

https://github.com/itsWindows11/Fluent-Screen-Recorder/blob/ui-refresh/FluentScreenRecorder/Views/SettingsPage.xaml#L86

**Comment by onein528** [comment]
Created [PR](https://github.com/itsWindows11/Fluent-Screen-Recorder/pull/1).

**Comment by itsWindows11** [comment]
Closed because there are too many conflicts to handle, also the work will move to another PR.

**Pull request closed without merging**
