### PR TITLE
PT-br Lang in App

### PR DESCRIPTION
**Pull request by maisondasilva**
Portuguese Brazilian

### CODE REVIEW

**Comment by maisondasilva** [comment]
@MarcAnt01 you can send it is ready.

**Comment by MarcAnt01** [comment]
@maisondasilva did you follow the guide and do everything in visual studio? If I open the files in Visual studio it doesn't display the translated language, this most likely because you created the .resw file manually (it needs to be created by VS after running a build) and you probably did the same with the .xlf file

**Comment by maisondasilva** [comment]
I used the 2022 version do I need to use the 2017 version to have no problem?

**Comment by MarcAnt01** [comment]
image

**Comment by MarcAnt01** [comment]
It might be that you haven't installed MAT

**Pull request closed without merging**
