### PR TITLE
Add microphone audio recording and additional refactoring

### PR DESCRIPTION
**Pull request by Jaiganeshkumaran**
Implements audio recording as part of #10

### CODE REVIEW

**Comment by Jaiganeshkumaran** [comment]
Currently, the code is really bad. You manually change the properties of controls and it's hard to read. I will add MVVM to make it easier.

**Comment by MarcAnt01** [comment]
> Currently, the code is really bad. You manually change the properties of controls and it's hard to read. I will add MVVM to make it easier.

I have never worked with MVVM, what advantages will it bring?

**Comment by Jaiganeshkumaran** [comment]
@MarcAnt01 With MVVM you only focus on the logic mostly in code behind and use x:Bind Mode one way or two way to change properties instead of changing it manually. This should make the code easier to read since you don't deal with the user interface that much and everything is done for you.

**Comment by Jaiganeshkumaran** [comment]
@MarcAnt01 One question, why do you resize the window? It looks bad on my 40-inch screen.

**Comment by MarcAnt01** [comment]
@Jaiganeshkumaran can you attach a screenshot? I have mostly studied the resizing in my 2:3 Surface Book 2

**Comment by Jaiganeshkumaran** [comment]
I need to scroll just to see very little options.

**Comment by MarcAnt01** [comment]
Yeah, on a big screen it doesn't look that great, but in small laptops/tablets, it looks quite good to me.
image

**Comment by MarcAnt01** [comment]
I tried making the window bigger, but with lots of options incoming that's not really a good idea. I also thought about moving the settings to a separated view, but that way it'll require more clicks for changing the options.

**Comment by Jaiganeshkumaran** [comment]
@MarcAnt01 Let the users change the window size. Don't do it yourself at starting. Also, we could have a PIP mode that acts like now.

**Comment by MarcAnt01** [comment]
@Jaiganeshkumaran do you mean always on top overlay mode?

**Comment by Jaiganeshkumaran** [comment]
@MarcAnt01 Yes

**Comment by Jaiganeshkumaran** [comment]
The main issue for me is that when you use a small screen, you could sit close to it so it will seem large enough however on a large screen you have more distance so it's really hard to see the small window.

**Comment by MarcAnt01** [comment]
I tried it, but the result was quite bad, I couldn't customize height and width, so the app looked very weird. I'll try to attach some screenshots if I find them

**Comment by MarcAnt01** [comment]
> The main issue for me is that when you use a small screen, you normally sit close to it so it will seem large enough however on a large screen you have more distance so it's really hard to see the small window.

I'll look into. Maybe setting a default window size that can be customized by users is a better idea.

**Comment by MarcAnt01** [comment]
As for the conflicts, sorry, but I forgot to push the changes I've done before

**Comment by MarcAnt01** [comment]
Once I add the localSetting for the toggle switch, I'm done, so I suggest you to wait for me to do that before resolving them

**Comment by Jaiganeshkumaran** [comment]
@MarcAnt01 You don't need to set any default window size or anything. Windows remembers the size you last kept the window and restores it unless you manually change it.

**Comment by MarcAnt01** [comment]
> @MarcAnt01 You don't need to set any default window size or anything. Windows remembers the size you last kept the window and restores it unless you manually change it. Just keep it as a regular application.

Yes, but I still would like to recommend a small window when launching the application. The thing is that if you use the app in full screen mode the ui is unpleasant.

**Comment by Jaiganeshkumaran** [comment]
@MarcAnt01 After adding more options, you'll find to use it full-screen mode rather than a small window.

**Comment by Jaiganeshkumaran** [comment]
@MarcAnt01 Or check the screen size and change the screen size based on it. A UWP app must be usable on all screen sizes.

**Comment by MarcAnt01** [comment]
Finished pushing now

**Comment by Jaiganeshkumaran** [comment]
@MarcAnt01 But now the resolve conflicts is grayed out and I still have conflicts.

**Comment by Jaiganeshkumaran** [comment]
I'm now working on first to make it MVVM based before fixing the audio issues with this PR.

**Comment by Jaiganeshkumaran** [comment]
@MarcAnt01 Are you planning to translate the app into other languages. Just asking because instead of just writing the string in code, I could put it in a resource file even if it's not translated.

**Comment by Jaiganeshkumaran** [comment]
@MarcAnt01 In the first panel there's an empty text block with no name. What's that for?

**Comment by MarcAnt01** [comment]
I should have solved the conflicts via force push

**Comment by MarcAnt01** [comment]
I don't understand why GitHub keeps showing conflicts even if I have solved them, whatever feel free to work on the PR, I'll fix them when merging

**Pull request closed without merging**
